# src/tamil_to_tanglish/converter.py

from .mapping import CHAR_MAP, PULLI

# The English vowel sounds generated by Tamil vowel signs
VOWEL_SIGNS_LIST = ['aa', 'i', 'ee', 'u', 'oo', 'e', 'ai', 'o', 'au']

def tamil_to_tanglish(text):
    result = ""
    i = 0
    length = len(text)
    
    while i < length:
        char = text[i]
        
        if char in CHAR_MAP:
            if i + 1 < length:
                next_char = text[i + 1]
                mapped_char = CHAR_MAP[char]
                
                # If the current character is a consonant (ends with 'a' in our map)
                if mapped_char.endswith('a') and len(mapped_char) > 0:
                    
                    # If the next character is a vowel sign, replace the inherent 'a'
                    if next_char in CHAR_MAP and CHAR_MAP[next_char] in VOWEL_SIGNS_LIST:
                        base_consonant = mapped_char[:-1]  # Strip the 'a'
                        result += base_consonant + CHAR_MAP[next_char]
                        i += 2
                        continue
                        
                    # If the next character is a Pulli (்), strip the 'a' completely
                    elif next_char == PULLI:
                        base_consonant = mapped_char[:-1]  # Strip the 'a'
                        result += base_consonant
                        i += 2
                        continue
            
            # Default case: add the mapped character
            result += CHAR_MAP[char]
        else:
            # Keep spaces, numbers, and English punctuation as they are
            result += char
            
        i += 1
        
    return result

# Local testing block
if __name__ == "__main__":
    test_text = "வணக்கம்" # vanakkam
    test_text_2 = "தமிழ்" # thamizh
    
    print(f"Tamil: {test_text} -> Tanglish: {tamil_to_tanglish(test_text)}")
    print(f"Tamil: {test_text_2} -> Tanglish: {tamil_to_tanglish(test_text_2)}")
  
